#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2023 Sebastian Gniazdowski
#
fetch() {
    # Preamble – emulate & 0=…
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}:A}
    source $0:h:h/share/preamble.inc.zsh --fun

    local -a opts; local -A Opts
    int/nc::parse-opts "C: -dir: p -progress q -quiet" Opts opts "$@"||\
        {iqerr incorrect options given to {cmd}fetch{%}; return 7}
    set -- "$reply[@]"
    int/nc::opt-cascade Opts -C --dir -p --progress -q --quiet
    int/nc::reset

    int/nc::get-file "$opts[@]" -- "$@"

    return $?
}
fetch "$@"
# vim:ft=zsh:sw=4:sts=4:et
