#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2018 Sebastian Gniazdowski
#
prj-dir() {
    # Preamble – emulate & 0=…
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}:A}
    source $0:h:h/share/preamble.inc.zsh --fun

    local -a opts; local -A Opts
    int/nc::parse-opts "q -quiet v -verbose" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/nc::opt-cascade Opts -q --quiet -v --verbose
    int/nc::reset
    integer retval

    if int/nc::get-prj-dir $opts;then
        if (($+Opts[--verbose]));then
            iqnotice -Q found project at {path}$REPLY{%}, it was one \
                of {num}$#reply{%} candidates
        elif ((!$+Opts[--quiet]));then
                builtin print -r -- $REPLY
        fi
    else
        retval=15
    fi

    return retval
}
prj-dir "$@"
# vim:ft=zsh:sw=4:sts=4:et
